services:
  # --- BASE DE DATOS ---
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-tiendasgo
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TiendasGo2026!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      # Mapeo directo para persistencia en tu carpeta local
      - ./db/DB_TiendasGo:/var/opt/mssql/tiendasgo_db
    command: /opt/mssql/bin/sqlservr -T272
  # --- MICROSERVICIOS (BACKEND) ---
  
  # 1. Auth & Core
  tg-auth-core:
    build: ./tg-auth-core
    container_name: ms-auth-core
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=TiendasGo;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=TiendasGo2026!
    depends_on:
      - sqlserver

  # 2. Catalog & Logistics
  tg-catalog-logistics:
    build: ./tg-catalog-logistics
    container_name: ms-catalog-logistics
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=TiendasGo;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=TiendasGo2026!
    depends_on:
      - sqlserver

  # 3. Purchases
  tg-purchases:
    build: ./tg-purchases
    container_name: ms-purchases
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=TiendasGo;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=TiendasGo2026!
    depends_on:
      - sqlserver

  # --- FRONTEND ---
  tg-frontend:
    build: ./tg-frontend
    container_name: front-tiendasgo
    ports:
      - "4200:80"
    depends_on:
      - tg-auth-core
      - tg-catalog-logistics
      - tg-purchases