server:
  port: 8081  #8081 para que no choque con el Auth (8080)

project:
  jwt:
    # Configurar variable de entorno JWT_SECRET
    secret: ${JWT_SECRET}
    # Tiempo de expiración: 86,400,000 ms = 24 Horas
    expiration: 86400000

spring:
  application:
    name: tg-catalog-logistics

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=TiendasGo;encrypt=true;trustServerCertificate=true
    username: sa
    # Configurar variable de entorno DB_PASSWORD
    password: ${DB_PASSWORD:TiendasGo2026!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: catalog





# No olvidar borrar el DEBUG


logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.orm.deprecation: ERROR
    com.tiendasgo.catalog.config.security.jwt: DEBUG
